### PR TITLE
Ben

### PR DESCRIPTION
**Pull request by Bendistocratic**
Like seriously dk what query_content is, ~so I'm just gonna assume that it is you query it and it returns the ip address and port of the peer you're allocated to.~ (Refer to comment below)

The list directory files should be option 1 and not 2.

P.S. -- not tested yet because I require the recv in P2pClient.py

### CODE REVIEW

**Comment by peng229** [comment]
@Bendistocratic Tracker.py at line 72

Need to get rid of the "peer_id =" lol

**Comment by peng229** [comment]
For query 2:
2. List peers with the file you want
Enter: 2

In Tracker i have a file_owners dictionary maintained during advertise;
 that tracks which file is under which user i.e.
{'file1.txt': ['127.0.0.1:50139'], 'file2.txt': ['127.0.0.1:50139']} (of cos it will be unique id later)

so for query 2, we should let user input the file that he wants to check, then return based on the file_owners dictionary

**Comment by peng229** [comment]
that being said, i think there's a bug
the client.query_for_content() in Peer.py takes in no argument,
but in P2PClient
def query_for_content(self, peerId, fileName, fileChunkId):
here takes in 3 arguments
:)

**Comment by Bendistocratic** [comment]
> For query 2:
> 2. List peers with the file you want
> Enter: 2
> 
> In Tracker i have a file_owners dictionary maintained during advertise;
> that tracks which file is under which user i.e.
> {'file1.txt': ['127.0.0.1:50139'], 'file2.txt': ['127.0.0.1:50139']} (of cos it will be unique id later)
> 
> so for query 2, we should let user input the file that he wants to check, then return based on the file_owners dictionary

file_owners dictionary?
Right now query content will return:
- MESSAGE_TYPE
- PEER_IP_PORT
- CHUNK NUMBER
- FILE_NAME

**Pull request merged**
